name: facefade
description: "FaceFade - AI ile Dijital Anıları Dönüştür"
publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: '>=3.4.4 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  
  # UI Components
  cupertino_icons: ^1.0.6
  lottie: ^3.1.2
  photo_view: ^0.15.0
  flutter_staggered_grid_view: ^0.7.0
  
  # Media & Camera
  image_picker: ^1.0.8
  camera: ^0.10.5+9
  photo_manager: ^3.0.0
  
  # Permissions
  permission_handler: ^11.3.1
  
  # Storage & Cache
  shared_preferences: ^2.2.3
  path_provider: ^2.1.3
  
  # Firebase
  firebase_core: ^2.24.2
  firebase_auth: ^4.15.3
  cloud_firestore: ^4.13.6
  firebase_storage: ^11.5.6
  
  # HTTP & API
  http: ^1.1.2
  dio: ^5.4.0
  
  # State Management
  provider: ^6.1.1
  
  # Image Processing
  image: ^4.1.3
  
  # Video Processing
  video_player: ^2.8.1
  
  # Social Sharing
  share_plus: ^7.2.2
  
  # Face Detection (on-device)
  google_mlkit_face_detection: ^0.9.0
  
  # Utils
  uuid: ^4.2.1
  intl: ^0.19.0
  loading_animation_widget: ^1.2.0+4
  
  # Animations
  flutter_animate: ^4.3.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^3.0.0

flutter:
  uses-material-design: true
  assets:
    - assets/images/
    - assets/animations/
  fonts:
    - family: OpenSans
      fonts:
        - asset: fonts/OpenSans-Regular.ttf
        - asset: fonts/OpenSans-Bold.ttf
          weight: 700 