services:
  - type: web
    name: facefade-backend
    env: python
    buildCommand: pip install -r requirements.txt
    startCommand: uvicorn main:app --host 0.0.0.0 --port $PORT
    envVars:
      - key: PYTHON_VERSION
        value: 3.11.0
      - key: PORT
        generateValue: true
    disk:
      name: facefade-storage
      mountPath: /opt/render/project/src/temp_files
      sizeGB: 1 